python3 ./py_folder/train_hal.py \
    --n_way $1 \
    --n_shot $2 \
    --n_aug $3 \
    --n_query_all $4 \
    --z_dim $5 \
    --fc_dim $5 \
    --n_train_class $6 \
    --extractor_folder $7 \
    --num_epoch $8 \
    --result_path . \
    --hallucinator_name HAL_PN_AFHN_1_tf1_ar1_m$1n$2a$3q$4_ep$8 \
    --AFHN \
    --lambda_meta 1.0 \
    --lambda_tf 1.0 \
    --lambda_ar 1.0
